name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  # Change this to 16 or 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      #- name: Build project
      #  run: npm run build

      - name: Debug build process
        run: npm run build || true

      - name: Verify build output
        run: |
          echo "Contents of dist folder:"
          ls dist  # Check if the folder exists

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Update this to match your output folder
